[project]
name = "twinleaf"
description = "Communications library and utilities for Twinleaf I/O (TIO) devices"
long_description = "Twinleaf I/O is a serialization for kilohertz-rate data from data-intensive sensors connected by serial ports. This package makes it easy to access all the features on these devices by bulding a convenient, discoverable python object that reflects all the data streams and settings on the conneted device."

requires-python = ">=3.12"
classifiers = [
    "Topic :: System :: Hardware :: Hardware Drivers",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
]
license = "MIT AND Apache-2.0"
license-files = [
  "LICENSE-APACHE.txt",
  "LICENSE-MIT.txt"
]
dynamic = ["version"]
dependencies = [
    "ipython>=9",
]
readme="README.md"

[project.scripts]
itl = "twinleaf.itl:interact"

[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "twinleaf._twinleaf"
python-source = "python"
