"""Type stub for the Rust extension module (twinleaf._twinleaf).

Mirrors the pyo3 bindings in rust/src/lib.rs. Keep in sync with the
`#[pymethods]`/`#[getter]` definitions there.
"""

from collections.abc import Iterator
from typing import Any

class _Rpc:
    @property
    def name(self) -> str: ...
    @property
    def readable(self) -> bool: ...
    @property
    def writable(self) -> bool: ...
    @property
    def size_bytes(self) -> int | None: ...
    @property
    def type_str(self) -> str: ...
    def __repr__(self) -> str: ...

class _RpcRegistry:
    def children_of(self, prefix: str) -> list[str]: ...
    def find(self, name: str) -> _Rpc | None: ...
    def suggest(self, query: str) -> list[str]: ...
    def search(self, query: str) -> list[str]: ...
    @property
    def hash(self) -> int | None: ...
    def __repr__(self) -> str: ...

class _Device:
    def __new__(
        cls, root_url: str | None = ..., route: str | None = ...
    ) -> _Device: ...
    @property
    def _url(self) -> str: ...
    @property
    def _route(self) -> str: ...
    def _rpc(self, name: str, req: bytes) -> bytes: ...
    def _rpc_list(self) -> list[Any]: ...
    def _rpc_registry(self) -> _RpcRegistry: ...
    def _capture(
        self,
        name: str,
        timeout_seconds: float,
        raw: bool,
    ) -> Any: ...
    def _samples(
        self,
        n: int | None = ...,
        stream: str | None = ...,
        columns: list[str] | None = ...,
    ) -> Iterator[dict[str, Any]]: ...
    def _get_metadata(self) -> dict[str, Any]: ...
